### PR TITLE
Subject line wrap

### PR DESCRIPTION
**Pull request by stefanha**
Fixes: #81

### CODE REVIEW

**Comment by stefanha** [comment]
@ehabkost Does the run_tests.sh change look good to you?

**Comment by elmarco** [comment]
works for me

**Comment by elmarco** [comment]
wait, I got that:

```
Traceback (most recent call last):
  File "/home/elmarco/bin/git-publish", line 911, in <module>
    sys.exit(main())
  File "/home/elmarco/bin/git-publish", line 861, in main
    open(cover_letter_path, 'wb').write(msg.as_bytes())
  File "/usr/lib64/python3.7/email/message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python3.7/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 214, in _dispatch
    meth(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 432, in _handle_text
    super(BytesGenerator,self)._handle_text(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 249, in _handle_text
    self._write_lines(payload)
  File "/usr/lib64/python3.7/email/generator.py", line 155, in _write_lines
    self.write(line)
  File "/usr/lib64/python3.7/email/generator.py", line 406, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
```

**Comment by stefanha** [comment]
> wait, I got that with this branch:
> 
> ```
> ...
>   File "/usr/lib64/python3.7/email/generator.py", line 406, in write
>     self._fp.write(s.encode('ascii', 'surrogateescape'))
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 9: ordinal not in range(128)
> ```

Thanks for reporting this.  I've pushed a new version that uses EmailMessage.get/set_content() instead of EmailMessage.get/set_payload().  Character set encoding should now be handled correctly.

Does this fix it for you?

**Comment by elmarco** [comment]
```
Traceback (most recent call last):
  File "/home/elmarco/bin/git-publish", line 911, in <module>
    sys.exit(main())
  File "/home/elmarco/bin/git-publish", line 858, in main
    body = msg.get_content().replace('*** BLURB HERE ***', blurb)
AttributeError: 'Message' object has no attribute 'get_content'
```

**Comment by stefanha** [comment]
@elmarco Thank you!  An old Message object was being returned instead of the modern EmailMessage.  I've fixed this by explicitly using email.policy.SMTP instead of the implicit compat32 policy.  Hope this solves the issue for you?

**Comment by ehabkost** [comment]
> @ehabkost Does the run_tests.sh change look good to you?

Sorry for taking so long to reply. It looks good to me.

**Pull request merged**
