### PR TITLE
Allow to edit "To" list (just like "Cc" list), and save them when edited

### PR DESCRIPTION
**Pull request by xzpeter**
These tiny small patches are basically trying to add two new functions:

1. Allow us to edit "To" list as well, just like we can edit "Cc" list.
1. When user edited either "To" or "Cc" list, store them permanantly.

### CODE REVIEW

**Comment by stefanha** [comment]
This series can be simplified: only patches 2 and 4 are necessary.

Please don't pass the options object to functions.  It exposes too many variables and hides side effects when functions modify the object.

Follow the existing approach where cc is a set() object.  set() objects are mutable so the caller sees the updated values when a helper function has modified the set.  It is not necessary to call git_set_config('branch', topic, 'gitpublishto', to) from multiple places.

Do you see what I mean that only patches 2 and 4 are necessary?

**Comment by xzpeter** [comment]
On Wed, Nov 30, 2016 at 10:41 PM, Stefan Hajnoczi <notifications@github.com>
wrote:

> This series can be simplified: only patches 2 and 4 are necessary.
>
> Please don't pass the options object to functions. It exposes too many
> variables and hides side effects when functions modify the object.
>
Follow the existing approach where cc is a set() object. set() objects are
> mutable so the caller sees the updated values when a helper function has
> modified the set. It is not necessary to call git_set_config('branch',
> topic, 'gitpublishto', to) from multiple places.
>

The problem is that we have these lines in the big "try":

        except (GitSendEmailError, GitHookError, InspectEmailsError):
            return 1

If user hit "q", we'll directly return here, without reaching the code to
save the to and cc list. So currently if we edit cc list, then hit "q", cc
list won't be kept.

Thanks,

-- peterx

**Comment by xzpeter** [comment]
On Wed, Nov 30, 2016 at 10:41 PM, Stefan Hajnoczi <notifications@github.com>
wrote:

> This series can be simplified: only patches 2 and 4 are necessary.
>
> Please don't pass the options object to functions. It exposes too many
> variables and hides side effects when functions modify the object.
>
> Follow the existing approach where cc is a set() object. set() objects are
> mutable so the caller sees the updated values when a helper function has
> modified the set. It is not necessary to call git_set_config('branch',
> topic, 'gitpublishto', to) from multiple places.
>
> Do you see what I mean that only patches 2 and 4 are necessary?
>
Or, do you like me to move the to/cc store lines into the "finally" block?
In that case, it should be called even if user hit "q", and we can do it in
3 patches instead of 5 (use old patch 2, patch 4, and another new patch to
move it into "finally").

Thanks,

**Comment by stefanha** [comment]
On Wed, Nov 30, 2016 at 3:17 PM, Peter Xu <notifications@github.com> wrote:
> On Wed, Nov 30, 2016 at 10:41 PM, Stefan Hajnoczi <notifications@github.com>
> wrote:
> > This series can be simplified: only patches 2 and 4 are necessary.
> >
> > Please don't pass the options object to functions. It exposes too many
> > variables and hides side effects when functions modify the object.
> >
> > Follow the existing approach where cc is a set() object. set() objects are
> > mutable so the caller sees the updated values when a helper function has
> > modified the set. It is not necessary to call git_set_config('branch',
> > topic, 'gitpublishto', to) from multiple places.
> >
> > Do you see what I mean that only patches 2 and 4 are necessary?
> >
> Or, do you like me to move the to/cc store lines into the "finally" block?
> In that case, it should be called even if user hit "q", and we can do it in
> 3 patches instead of 5 (use old patch 2, patch 4, and another new patch to
> move it into "finally").

No, using finally feels like a hack.  It is cleanest to explicitly
save To/Cc in inspect_menu().  I just didn't think about the case
where the user cancels but still wants to save the To/Cc changes :).

Please include a comment so it's clear that we're saving immediately
because the user might cancel.  Please also avoid passing options
around.

Thanks,
Stefan

**Comment by xzpeter** [comment]
I'll close this one and send v2. :)

**Pull request closed without merging**
