### PR TITLE
Fixes git-publish on Windows.

### PR DESCRIPTION
**Pull request by lygstate**
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

**Review by stefanha — CHANGES_REQUESTED** [review]
Thanks for submitting this. Can you provide details on the issue? Which output caused problems?

I would like to understand the nature of the bug. The \r\n vs \n vs \r is a common issue on Windows, but I was surprised that stdout/stderr also needs to split on backslash and forward slash (maybe this is related to filenames?).

**Comment by lygstate** [comment]
It's return an empty list, that means not split at all
```
E:\CI-Cor-Ready\xemu\qemu.org>python git-publish.py --to qemu-devel@nongnu.org --cc "Paolo Bonzini <pbonzini@redhat.com>,Daniel P. Berrangé <berrange@redhat.com>"
Traceback (most recent call last):
  File "git-publish.py", line 905, in <module>
    sys.exit(main())
  File "git-publish.py", line 632, in main
    if not check_profile_exists(options.profile_name):
  File "git-publish.py", line 330, in check_profile_exists
    lines = git_config_with_profile('--get-regexp', '^gitpublishprofile\\.%s\\.' % profile_name)
  File "git-publish.py", line 290, in git_config_with_profile
    gitpublish = os.path.abspath(os.path.join(git_get_toplevel_dir(), '.gitpublish'))
  File "git-publish.py", line 149, in git_get_toplevel_dir
    GIT_TOPLEVEL = _git_check('rev-parse', '--show-toplevel')[0]
IndexError: list index out of range

E:\CI-Cor-Ready\xemu\qemu.org>pause
请按任意键继续. . .

```

`git rev-parse --show-toplevel`
result
```
E:/CI-Cor-Ready/xemu/qemu.org\r\n
```

**Comment by stefanha** [comment]
Please add the following into popen_lines() below "stdout, stderr = cmd.communicate(**kwargs)":
```python
    print(repr(stdout))
    print(repr(stderr))
    print(repr(os.linesep))
```

On Windows os.linesep should be '\r\n'. The `git rev-parse --show-toplevel` output you showed terminates with \r\n but in that case popen_lines() should have worked correctly, so something is missing. Hopefully looking at the exact repr output from Python will reveal the issue...

Thanks!

**Comment by lygstate** [comment]
```
"
b'E:/CI-Cor-Ready/xemu/qemu.org\n'
b''
'\r\n'
Traceback (most recent call last):
  File "git-publish.py", line 908, in <module>
    sys.exit(main())
  File "git-publish.py", line 635, in main
    if not check_profile_exists(options.profile_name):
  File "git-publish.py", line 333, in check_profile_exists
    lines = git_config_with_profile('--get-regexp', '^gitpublishprofile\\.%s\\.' % profile_name)
  File "git-publish.py", line 293, in git_config_with_profile
    gitpublish = os.path.abspath(os.path.join(git_get_toplevel_dir(), '.gitpublish'))
  File "git-publish.py", line 152, in git_get_toplevel_dir
    GIT_TOPLEVEL = _git_check('rev-parse', '--show-toplevel')[0]
IndexError: list index out of range

```

**Comment by stefanha** [comment]
Thanks for posting the output. I have confirmed that git always uses '\n' even on Windows by checking the git source code (it uses the stream _set_fmode() _O_BINARY setting).

Does the following patch fix the issue for you?
```diff
diff --git a/git-publish b/git-publish
index 1920979..4ebb882 100755
--- a/git-publish
+++ b/git-publish
@@ -55,8 +55,10 @@ def to_text(data):
 def popen_lines(cmd, **kwargs):
     '''Communicate with a Popen object and return a list of lines for stdout and stderr'''
     stdout, stderr = cmd.communicate(**kwargs)
-    stdout = stdout.decode(ENCODING).split(os.linesep)[:-1]
-    stderr = stderr.decode(ENCODING).split(os.linesep)[:-1]
+
+    # Use '\n' instead of os.linesep because git always emits '\n', even on Windows
+    stdout = stdout.decode(ENCODING).split('\n')[:-1]
+    stderr = stderr.decode(ENCODING).split('\n')[:-1]
     return stdout, stderr
 
 def _git_check(*args):
```

**Comment by lygstate** [comment]
I think my patch are better， it can split lines despite.the os

**Comment by stefanha** [comment]
On Sun, Aug 30, 2020 at 10:39 AM Yonggang Luo <notifications@github.com>
wrote:

> I think my patch are better， it can split lines despite.the os
>
Why does the patch split lines on '\r', I'm not aware of a modern OS that
uses that line ending?

**Comment by lygstate** [comment]
Windows, and DOS before it, uses a pair of CR and LF characters to terminate lines (0x0D0A).

UNIX (Including Linux and FreeBSD) uses an LF character only (0x0A).

OSX also uses a single LF character(0x0A), but the classic Mac operating system used a single CR character for line breaks(0x0D).

作者：Hackjutsu
链接：https://www.jianshu.com/p/a28736f798a5
來源：简书
简书著作权归作者所有，任何形式的转载都请联系作者获得授权并注明出处。

**Comment by stefanha** [comment]
@lygstate Do git and Python 3 run on Classic Mac OS?

There are [even more newline characters](https://en.wikipedia.org/wiki/Newline#Representation) so we need a way to decide which ones to include. I would rather not include line terminators for obsolete operating systems where git-publish doesn't run.

Your patch without the '\r' and with a comment explaining why os.linesep isn't enough would be good:
```python
# git emits '\n' even on Windows so don't rely on os.linesep
```

**Comment by stefanha** [comment]
Thank you!

**Pull request merged**
